import { Inter } from "next/font/google";
import { PaginateProvider } from "@/context/PaginateContext";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Projectly",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <PaginateProvider>
        <body className={inter.className}>{children}</body>
      </PaginateProvider>
    </html>
  );
}
